export { Certificate } from './certificate'
export { CourseContent } from './course'
export { CoursesLayout } from './courses'
export { Dashboard } from './dashboard'
export { Landing } from './landing'
export { WelcomeLayout, WelcomeContent } from './welcome'
